// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zeus LH01 la san pham mu bao hiem xe dap cua cong ty Long Huei – Nha san xuat mu bao hiem voi hon 30 nam kinh nghiem",
                            Name = "",
                            PictureUrl = "images/products/muxedap-zues1.png",
                            Price = 200m,
                            ProductBrandId = 1,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Duoc thiet ke co nhieu lo thoang khi, phu hop voi nguoi choi the thao va di xe dap nen non co khoi luong sieu nhe. Chi khoang 265g.",
                            Name = "Non Xe Dap Zeus ST   ",
                            PictureUrl = "images/products/muxedap-zues2.png",
                            Price = 150m,
                            ProductBrandId = 1,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vua ra mat giua nam nay (2022) nhung rat thu hut su quan tam cua khach hang. Day la mau non xe dap don gian, gon nhe.",
                            Name = "Non Xe Dap Yohe MD15 Trang",
                            PictureUrl = "images/products/muxedap-yohe2.png    ",
                            Price = 180m,
                            ProductBrandId = 2,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thiet ke don gian, gon nhe, lo thong gio duoc thiet ke kieu dang khi dong hoc mang lai cam giac thong thoang.",
                            Name = "Non Xe Dap Yohe MH16 Xam to ong",
                            PictureUrl = "images/products/muxedap-yohe1.png",
                            Price = 300m,
                            ProductBrandId = 2,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dung nhu ten goi no duoc thiet ke co luoi trai cach dieu bang vai phia truoc co the thao roi duoc. Form non gon nhe phu hop cho ca nguoi lon va tre em.",
                            Name = "Non Xe Dap Sunda F05 Hong Phan",
                            PictureUrl = "images/products/muxedap-sunda1.png    ",
                            Price = 250m,
                            ProductBrandId = 4,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lop lot thoai mai va cam giu dang tot, khong gay ap luc len dau hoac mat, lop dem duoc che tao bang vat lieu Poly Source nen duoi ap suat cao.",
                            Name = "Non Xe Dap Royal R16",
                            PictureUrl = "images/products/muxedap-royal1.png    ",
                            Price = 120m,
                            ProductBrandId = 5,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Non fullface Yohe 981 voi 2 kinh chan duoc ra mat nham thay the model Yohe 970 da lam nen ten tuoi trong gioi Biker.",
                            Name = "Non FullFace Yohe",
                            PictureUrl = "images/products/fullface-yohe1.png",
                            Price = 10m,
                            ProductBrandId = 2,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Mu Fullface Sunda 811 co form non va chat luong tuong duong voi mu fullface Yohe 978 dang rat HOT hien nay nhung co gia thap nhieu.",
                            Name = "Non FullFace Sunda 811 Xanh Nham",
                            PictureUrl = "images/products/fullface-sunda1.png",
                            Price = 8m,
                            ProductBrandId = 4,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mu bao hiem Fullface 2 kinh Sunda 823 duoc cau thanh tu chat lieu ABS nguyen sinh, cho do ben bi, dan hoi cao, chong chiu luc tac dong cuc tot . ",
                            Name = "Non FullFace Sunda 823 Xam Nham",
                            PictureUrl = "images/products/fullface-sunda2.png",
                            Price = 15m,
                            ProductBrandId = 4,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = " Se dac biet phu hop voi nhung ai yeu thich su gon gang, linh dong. Co the su dung trong tap Gym hoac choi cac mon the thao.",
                            Name = "Gang tay TORC Vang",
                            PictureUrl = "images/products/glove-torc1.png",
                            Price = 18m,
                            ProductBrandId = 3,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Được làm từ da lộn kết hợp vải cotton cao cấp. Có miếng đệm dưới lòng bàn tay tạo ma sát giúp cầm nắm dễ dàng hơn.",
                            Name = "Găng tay TORC Xanh",
                            PictureUrl = "images/products/glove-torc2.png",
                            Price = 15m,
                            ProductBrandId = 3,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "la gang tay dai ngon duoc lam chu yeu tu da, co gu duoc lam tu chat lieu Titanium.",
                            Name = "Gang tay Sunda Trang",
                            PictureUrl = "images/products/glove-sunda1.png",
                            Price = 16m,
                            ProductBrandId = 4,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Polyester thoang mat va lop thun co gian ho tro thoang khi rat tot. Cac gu cao su ban tay va dot ngon tay duoc may an ben trong lop vai khien SUOMY SU-09 nhin rat bat mat.",
                            Name = "Gang tay Sunda Cam",
                            PictureUrl = "images/products/glove-sunda2.png",
                            Price = 14m,
                            ProductBrandId = 4,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "duoc cau thanh tu nhua ABS nguyen sinh, chat lieu giup non co trong luong nhe nhung dong thoi mang lai su cung cap, kha nang hap thu xung dong va phan tan luc khi co tac dong manh.",
                            Name = "Non Ba Phan Tu ROC Trang",
                            PictureUrl = "images/products/baphantu-roc1.png",
                            Price = 250m,
                            ProductBrandId = 6,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Vo non Yohe 852 Den Bong duoc lam tu nhua ABS nguyen sinh cao cap, co do dan hoi va chong chiu va dap tot. La loai nhua chuyen dung trong san xuat Mu bao hiem, thiet bi y te…",
                            Name = "Non Ba Phan Tu YoHe Den",
                            PictureUrl = "images/products/baphantu-yohe1.png",
                            Price = 189.99m,
                            ProductBrandId = 2,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Duoc lam tu nhua ABS nguyen sinh cao cap, co do dan hoi va chong chiu va dap tot. La loai nhua chuyen dung trong san xuat Mu bao hiem, thiet bi y te…",
                            Name = "Non Ba Phan Tu YoHe Xam",
                            PictureUrl = "images/products/baphantu-yohe2.png",
                            Price = 199.99m,
                            ProductBrandId = 2,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Non Zues duoc tao ra voi su sang tao va dot pha tu cong nghe in 3D co do ben cao voi nhua cao cap",
                            Name = "Non Ba Phan Tu Zues Trang",
                            PictureUrl = "images/products/baphantu-zues2.png",
                            Price = 150m,
                            ProductBrandId = 1,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            Description = "Non Zues duoc tao ra voi su sang tao va dot pha tu cong nghe in 3D co do ben cao voi nhua cao cap",
                            Name = "Non Ba Phan Tu Zues Xam",
                            PictureUrl = "images/products/baphantu-zues1.png",
                            Price = 180m,
                            ProductBrandId = 1,
                            ProductTypeId = 3
                        });
                });

            modelBuilder.Entity("Core.Models.Domain.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ZUES"
                        },
                        new
                        {
                            Id = 2,
                            Name = "YOHE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TORC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SUNDA"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ROYAL"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ROC"
                        });
                });

            modelBuilder.Entity("Core.Models.Domain.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MuXeDap"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FullFace"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BaPhanTu"
                        },
                        new
                        {
                            Id = 4,
                            Name = "GangTay"
                        });
                });

            modelBuilder.Entity("Core.Models.Domain.Product", b =>
                {
                    b.HasOne("Core.Models.Domain.ProductBrand", "ProductBrand")
                        .WithMany()
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Domain.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
